version: '3.8'
services:
  php-apache-environment:
    image: chafidhotur/matuku
    container_name: matuku
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kopi
      MYSQL_DATABASE: matuku
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./matuku.sql:/docker-entrypoint-initdb.d/matuku.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    name: backend-network
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24